// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title IGroth16Verifier
 * @notice Interface for Groth16 proof verification
 * @dev All ZK verifier contracts generated by snarkjs implement this interface
 *
 * The verifyProof function takes the proof components and public signals
 * and returns true if the proof is valid.
 *
 * Proof components:
 * - a[2]: First G1 point of the proof
 * - b[2][2]: G2 point of the proof (note: reversed order for pairing)
 * - c[2]: Second G1 point of the proof
 * - input[]: Public signals array (size depends on circuit)
 */
interface IGroth16Verifier {
    /**
     * @notice Verify a Groth16 proof
     * @param _pA First G1 point (2 elements)
     * @param _pB G2 point (2x2 elements, note: order is reversed)
     * @param _pC Second G1 point (2 elements)
     * @param _pubSignals Public signals array
     * @return True if the proof is valid
     */
    function verifyProof(
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[] calldata _pubSignals
    ) external view returns (bool);
}

/**
 * @title IDateRangeVerifier
 * @notice Interface for DateRange circuit verifier
 * @dev Public signals: [credentialCommitment, rangeStart, rangeEnd, fieldIndex]
 */
interface IDateRangeVerifier {
    function verifyProof(
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[4] calldata _pubSignals
    ) external view returns (bool);
}

/**
 * @title IValueRangeVerifier
 * @notice Interface for ValueRange circuit verifier
 * @dev Public signals: [credentialCommitment, minValue, maxValue, fieldIndex]
 */
interface IValueRangeVerifier {
    function verifyProof(
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[4] calldata _pubSignals
    ) external view returns (bool);
}

/**
 * @title IAgeThresholdVerifier
 * @notice Interface for AgeThreshold circuit verifier
 * @dev Public signals: [credentialCommitment, threshold, currentTimestamp, comparisonType]
 */
interface IAgeThresholdVerifier {
    function verifyProof(
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[4] calldata _pubSignals
    ) external view returns (bool);
}

/**
 * @title ICompoundProofVerifier
 * @notice Interface for CompoundProof circuit verifier (2 disclosures)
 * @dev Public signals: [commitment, types[2], params[2][4]] = 11 signals
 */
interface ICompoundProofVerifier {
    function verifyProof(
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[11] calldata _pubSignals
    ) external view returns (bool);
}

/**
 * @title ICompoundProof3Verifier
 * @notice Interface for CompoundProof circuit verifier (3 disclosures)
 * @dev Public signals: [commitment, types[3], params[3][4]] = 16 signals
 */
interface ICompoundProof3Verifier {
    function verifyProof(
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[16] calldata _pubSignals
    ) external view returns (bool);
}

/**
 * @title ICompoundProof4Verifier
 * @notice Interface for CompoundProof circuit verifier (4 disclosures)
 * @dev Public signals: [commitment, types[4], params[4][4]] = 21 signals
 */
interface ICompoundProof4Verifier {
    function verifyProof(
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[21] calldata _pubSignals
    ) external view returns (bool);
}
